#!/bin/bash
0-current_working_directory,100-lets_move,101-clean_emacs,102-tree,103-commas,10-back,11-lists,12-file_type,14-copy_html,1-listit,2-bring_me_home,3-listfiles,4-listmorefiles,5-listfilesdigitonly,6-firstdirectory,7-movethatfile,__ls__,README.md,root@e8dad494c0a0:/alx-system_engine why?
